USE PLANT_WATERING_SYSTEM.PUBLIC;

CREATE OR REPLACE TABLE plant_data (
  plant_date DATETIME,
  soil INTEGER,
  humidity INTEGER,
  temperature INTEGER,
  message STRING
);

USE PLANT_WATERING_SYSTEM.PLANT;
CREATE NOTIFICATION INTEGRATION pubsub_notification
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = GCP_PUBSUB
  ENABLED = true
  GCP_PUBSUB_SUBSCRIPTION_NAME = 'projects/trim-heaven-415202/subscriptions/plant_watering_gcs_not-sub';

DESC NOTIFICATION INTEGRATION pubsub_notification;
DESC PIPE PLANT_WATERING_SYSTEM.PUBLIC.WATERING_PIPE

CREATE OR REPLACE PIPE PLANT_WATERING_SYSTEM.PUBLIC.WATERING_PIPE
  AUTO_INGEST = true
  INTEGRATION = pubsub_notification
  AS
COPY INTO PLANT_WATERING_SYSTEM.PUBLIC.PLANT_DATA
  FROM @plant_watering_system.public.watering_system_stage;

SELECT SYSTEM$PIPE_STATUS( 'PLANT_WATERING_SYSTEM.PUBLIC.WATERING_PIPE' )

  
  SELECT * FROM PLANT_WATERING_SYSTEM.PUBLIC.PLANT_DATA